configfile: "...../config/config_workflow.yaml"

##### load rules #####
include: "rules/fetch_data.smk"
include: "rules/data_analysis.smk"
include: "rules/emailer.smk"

##### target rules ######
rule all:
	input: expand("{latest_folder}/sent.txt", latest_folder=latest_folder)

